# start the build container in privileged mode, required for glibc. use ## to comment out
#BUILD_PRIVILEGED
# use default build container instead of bob-musl-busybox
#BUILD_FROM ${DEF_BUILD_CONTAINER}
FROM ${NAMESPACE}/busybox
MAINTAINER ${MAINTAINER}

ENV LANG en_US.utf8

ADD rootfs.tar /
RUN ldconfig
