FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

VOLUME [ "/var/lib/registry" ]

EXPOSE 5000

ENTRYPOINT ["/usr/libexec/docker-registry/registry"]
CMD ["serve", "/etc/docker/registry/config.yml.example"]
