FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

ADD docker-gen /etc/docker-gen/

ENV DOCKER_HOST=unix:///var/run/docker.sock \
    NGINX_ID=nginxproxy_nginx_1

CMD ["/bin/sh", "-c", "docker-gen -wait 5s -notify-sighup ${NGINX_ID} -watch /etc/docker-gen/nginx.tmpl /etc/nginx/sites-enabled/default.conf"]
