FROM ${IMAGE_PARENT}
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

EXPOSE 3000

VOLUME ["/opt/grafana/data"]

WORKDIR /opt/grafana

RUN ./bin/grafana-cli --pluginsDir "./data/plugins" plugins install grafana-piechart-panel

ENTRYPOINT ["./bin/grafana-server", "web"]
