FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

EXPOSE 3000

VOLUME ["/opt/grafana/data"]

WORKDIR /opt/grafana

RUN /usr/bin/grafana-cli --pluginsDir "/opt/grafana/data/plugins" plugins install grafana-piechart-panel

ENTRYPOINT ["/usr/bin/grafana-server"]
