FROM busybox:latest

LABEL maintainer="${MAINTAINER}"

COPY ${BOB_CURRENT_PORTAGE_FILE} /

RUN set -x && \
    mkdir -p /var/db/repos/ && \
    xzcat /${BOB_CURRENT_PORTAGE_FILE} | tar -xf - -C /var/db/repos && \
    mv /var/db/repos/portage /var/db/repos/gentoo && \
    mkdir -p /var/db/repos/gentoo/metadata && \
    rm /${BOB_CURRENT_PORTAGE_FILE}

VOLUME /var/db/repos /var/cache/eix
