FROM ${NAMESPACE}/stage3-import
MAINTAINER ${MAINTAINER}

ADD make.conf /etc/portage/make.conf

RUN mkdir -p /etc/portage/package.{mask,unmask,use,keywords}

ADD build-root.sh /bin/build-root

CMD ["/bin/bash"]
