FROM ${NAMESPACE}/nginx
MAINTAINER ${MAINTAINER}

VOLUME ["/etc/nginx/sites-enabled"]

# patch entr into s6 run file, restarts nginx when config changes
RUN sed -i 's/exec \/usr\/sbin\/nginx/ls \/etc\/nginx\/sites-enabled\/default.conf | entr -r \/usr\/sbin\/nginx/g' /etc/service/nginx/run
