FROM ${NAMESPACE}/s6
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

ADD etc /etc

RUN chmod +x $(find /etc/service -name run) && \
    ln -s /etc/s6_finish_default /etc/service/memcache/finish && \
    ln -s /etc/service/memcache /service

EXPOSE 11211

