#!/bin/sh

# create self signed certs if needed
if [ ! -f /etc/nginx/ssl/localhost/nginx.crt ] || [ ! -f /etc/nginx/ssl/localhost/nginx.key ]; then
    mkdir -p /etc/nginx/ssl/localhost
    CRT_COUNTRY="${CRT_COUNTRY:-DE}"
    CRT_STATE="${CRT_STATE:-SA}"
    CRT_LOCACTION="${CRT_LOCACTION:-MD}"
    CRT_ORG="${CRT_ORG:-ACME Inc - nginx}"
    CRT_CN="${CRT_CN:-nginx.local}"
    # rsa cert
    openssl req -new -x509 -nodes -days 3650 -newkey rsa:4069 \
        -subj "/C=${CRT_COUNTRY}/ST=${CRT_STATE}/L=${CRT_LOCACTION}/O=${CRT_ORG}/CN=${CRT_CN}" \
        -keyout /etc/nginx/ssl/localhost/nginx.key \
        -out /etc/nginx/ssl/localhost/nginx.crt
    # ecc cert
    openssl ecparam -name secp521r1 -genkey -param_enc explicit -out /etc/nginx/ssl/localhost/nginx-ecc.key
    openssl req -new -x509 -nodes -days 3650  \
        -subj "/C=${CRT_COUNTRY}/ST=${CRT_STATE}/L=${CRT_LOCACTION}/O=${CRT_ORG}/CN=${CRT_CN}" \
        -key /etc/nginx/ssl/localhost/nginx-ecc.key \
        -out /etc/nginx/ssl/localhost/nginx-ecc.crt
fi

# create dh parameters and enable forward secrecy
if [ "${NGINX_FORWARD_SECRECY}" = true ] && [ ! -f /etc/nginx/dh1024.pem ]; then
    openssl dhparam -out /etc/nginx/dh1024.pem 1024
    ln -s /etc/nginx/ssl_forward_secrecy.conf /etc/nginx/conf.d/
fi

# change UID/GID of nginx user if requested and not matching with actual values
# useful for dev setups to avoid permission headaches with mounted volumes
if [ ! -z ${NGINX_UID} ] && [ ! -z ${NGINX_GID} ]; then
    if [[ ! $(echo "${URL}" | grep "^nginx:x:${NGINX_UID}:${NGINX_GID}") ]]; then
        sed -i "s/^nginx:x:[0-9]*:[0-9]*:/nginx:x:${NGINX_UID}:${NGINX_GID}:/g" /etc/passwd
        sed -i "s/^nginx:x:[0-9]*:/nginx:x:${NGINX_GID}:/g" /etc/group
        chown -R nginx:nginx /var/lib/nginx
    fi
fi

# substitute ##_ENV_## marker in nginx site config files
# variables must start with NG_TMPL_
if $(printenv | grep -q "^NG_TMPL_"); then
    for config in $(find /etc/nginx/sites-enabled/ -name '*.conf'); do
        for tmpl_var in $(printenv | grep "^NG_TMPL_" | awk -F"=" '{print $1}'); do
            value=$(eval echo \$$tmpl_var)
            sed -i "s|##_${tmpl_var}_##|${value}|g" ${config}
        done
    done
fi

exec 2>&1
exec /usr/sbin/nginx -g 'daemon off;'
