FROM ${IMAGE_PARENT}
LABEL maintainer  ${MAINTAINER}

ADD rootfs.tar /

RUN dot -c && \
    rm -rf /var/lib/tomcat-9-local/webapps/ROOT/* && \
    echo '<% response.sendRedirect("/plantuml"); %>' > /var/lib/tomcat-9-local/webapps/ROOT/index.jsp
