FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

ENV SHELL=/bin/sh

RUN ldconfig && chmod +x $(find /etc/service -name run) && \
    chmod +x /etc/s6_finish_default && \
    ln -s /etc/s6_finish_default /etc/service/cron/finish && \
    ln -s /etc/s6_finish_default /etc/service/fs-watcher/finish && \
    ln -s /etc/s6_finish_default /etc/service/.s6-svscan/finish && \
    ln -s /etc/service/.s6-svscan /service

CMD ["/bin/s6-svscan", "-s", "-t0", "/service"]
