#!/bin/sh

ES_HOME=${ES_HOME:="/usr/share/elasticsearch"}
ES_USER=${ES_USER:="elasticsearch"}
ES_INSTANCE=local

PIDFILE="/run/elasticsearch/elasticsearch.${ES_INSTANCE}.pid"
ES_BASE_PATH="/var/lib/elasticsearch/${ES_INSTANCE}"
ES_PATH_CONF="/etc/elasticsearch/${ES_INSTANCE}"
ES_SCRIPT_PATH="/etc/elasticsearch/${ES_INSTANCE}/scripts"
ES_LOG_PATH="/var/log/elasticsearch/${ES_INSTANCE}"
ES_DATA_PATH="${ES_BASE_PATH}/data"

check_dirs="$(dirname ${PIDFILE}) ${ES_LOG_PATH} ${ES_SCRIPT_PATH} ${ES_DATA_PATH}"
for dir in ${check_dirs}; do
    [ ! -d "${dir}" ] && mkdir -p "${dir}"
    chown "${ES_USER}:${ES_GROUP}" "${dir}"
done;

export JAVA_HOME
export JAVA_OPTS
export ES_JVM_OPTIONS
export ES_JAVA_OPTS
export ES_STARTUP_SLEEP_TIME
export ES_PATH_CONF
export ES_USE_IPV4

server_command="/usr/share/elasticsearch/bin/elasticsearch"
server_args=" -p ${PIDFILE} -E path.data=${ES_DATA_PATH} -E path.logs=${ES_LOG_PATH}"
if [ -n "${ES_MAX_FD}" ]; then
    ulimit -n ${ES_MAX_FD}
fi

if [ -n "${MAX_MAP_COUNT}" -a -f /proc/sys/vm/max_map_count ]; then
                sysctl -q -w vm.max_map_count=${MAX_MAP_COUNT}
fi

exec 2>&1
su-exec elasticsearch:elasticsearch ${server_command} ${server_args}
