FROM ${NAMESPACE}/ruby-gcc
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

RUN gem install fluentd --no-ri --no-rdoc

RUN gem install fluent-plugin-elasticsearch --no-ri --no-rdoc

ADD etc /etc

WORKDIR /config
ADD docker-gen /config/template

RUN chmod +x $(find /etc/service -name run) && ln -s /etc/service/{docker-gen,fluentd} /service

CMD ["/bin/s6-svscan", "/service"]
