FROM scratch
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

RUN mkdir -p /etc/ssl/private && \
    mkdir -p /etc/ssl/certs && \
    openssl req -x509 -nodes -days 3650 -newkey rsa:4096 \
        -subj "/C=DE/ST=SA/L=MD/O=DevOps/CN=*.web.local" \
        -keyout /etc/ssl/private/nginx.key \
        -out /etc/ssl/certs/nginx.crt 

ADD etc /etc

ADD www /var/www

RUN chmod +x $(find /etc/service -name run) && ln -s /etc/service/* /service

EXPOSE 80

EXPOSE 443

CMD ["/bin/s6-svscan", "/service"]
