FROM ${NAMESPACE}/nginx
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

ADD etc /etc

# env for cert creation: CRT_COUNTRY, CRT_STATE, CRT_LOCATION, CRT_ORG, CRT_CN
ENV CRT_ORG ACME Inc - nginx-php

ADD www /var/www

RUN chmod +x $(find /etc/service -name run) && ln -s /etc/service/php-fpm /service

EXPOSE 80 443
