#!/bin/sh

if [ "${NGINX_RELOAD_ON_CONTAINER_SIGHUP}" = true ]; then
    # instead of shutting down the container just send a SIGHUP to nginx and carry on
    echo -e '#!/bin/sh\n[[ -f /run/nginx.pid ]] && pkill -HUP nginx' \
        > /etc/service/.s6-svscan/SIGHUP
fi

# create self signed certs if needed
if [ ! -f /etc/nginx/certs/default.crt ] || [ ! -f /etc/nginx/certs/default.key ]; then
    mkdir -p /etc/nginx/certs
    CRT_COUNTRY="${CRT_COUNTRY:-DE}"
    CRT_STATE="${CRT_STATE:-SA}"
    CRT_LOCACTION="${CRT_LOCACTION:-MD}"
    CRT_ORG="${CRT_ORG:-ACME Inc - nginx}"
    CRT_CN="${CRT_CN:-nginx.local}"
    # rsa cert
    openssl req -new -x509 -nodes -days 3650 -newkey rsa:4096 \
        -subj "/C=${CRT_COUNTRY}/ST=${CRT_STATE}/L=${CRT_LOCACTION}/O=${CRT_ORG}/CN=${CRT_CN}" \
        -keyout /etc/nginx/certs/default.key \
        -out /etc/nginx/certs/default.crt
    # ecc cert
    openssl ecparam -name secp521r1 -genkey -param_enc explicit -out /etc/nginx/certs/default.ecc.key
    openssl req -new -x509 -nodes -days 3650  \
        -subj "/C=${CRT_COUNTRY}/ST=${CRT_STATE}/L=${CRT_LOCACTION}/O=${CRT_ORG}/CN=${CRT_CN}" \
        -key /etc/nginx/certs/default.ecc.key \
        -out /etc/nginx/certs/default.ecc.crt
fi

# create dh parameters and enable forward secrecy
if [ "${NGINX_FORWARD_SECRECY}" = true ] && [ ! -f /etc/nginx/dh1024.pem ]; then
    openssl dhparam -out /etc/nginx/dh1024.pem 1024
    ln -s /etc/nginx/ssl_forward_secrecy.conf /etc/nginx/conf.d/
fi

# change UID/GID of nginx user if requested and not matching with actual values
# useful for dev setups to avoid permission headaches with mounted volumes
if [ ! -z ${NGINX_UID} ] && [ ! -z ${NGINX_GID} ]; then
    if [[ ! $(echo "${URL}" | grep "^nginx:x:${NGINX_UID}:${NGINX_GID}") ]]; then
        sed -i "s/^nginx:x:[0-9]*:[0-9]*:/nginx:x:${NGINX_UID}:${NGINX_GID}:/g" /etc/passwd
        sed -i "s/^nginx:x:[0-9]*:/nginx:x:${NGINX_GID}:/g" /etc/group
        chown -R nginx:nginx /var/lib/nginx
    fi
fi

if [ ! -z "${NGINX_REAL_IP_FROM}" ]; then
    sed -i -e 's|#real_ip_header X-Forwarded-For;|real_ip_header X-Forwarded-For;|g' \
        -e 's|#set_real_ip_from ##_NG_TMPL_REAL_IP_FROM_##;|set_real_ip_from ##_NG_TMPL_REAL_IP_FROM_##;|g' \
        /etc/nginx/sites-enabled/default.conf
    export NG_TMPL_REAL_IP_FROM="${NGINX_REAL_IP_FROM}"
fi

# substitute ##_ENV_## marker in nginx site config files
# variables must start with NG_TMPL_
if $(printenv | grep -q "^NG_TMPL_"); then
    for config in $(find /etc/nginx/sites-enabled/ -name '*.conf'); do
        for tmpl_var in $(printenv | grep "^NG_TMPL_" | awk -F"=" '{print $1}'); do
            value=$(eval echo \$$tmpl_var)
            sed -i "s|##_${tmpl_var}_##|${value}|g" ${config}
        done
    done
fi

exec 2>&1
exec /usr/sbin/nginx -g 'daemon off;'
