#!/bin/sh

ES_USER=${ES_USER:="elasticsearch"}
ES_INSTANCE=local

PIDFILE="/run/elasticsearch/elasticsearch.${ES_INSTANCE}.pid"
ES_BASE_PATH="/var/lib/elasticsearch/${ES_INSTANCE}"
ES_CONF_PATH="/etc/elasticsearch/${ES_INSTANCE}"
ES_LOG_PATH="/var/log/elasticsearch/${ES_INSTANCE}"

dir="$(dirname ${PIDFILE})"
if [ ! -d "${dir}" ]; then
        mkdir -p "${dir}"
fi
chown ${ES_USER} "${dir}"

ES_DATA_PATH="${ES_BASE_PATH}/data"
ES_WORK_PATH="${ES_BASE_PATH}/work"

export ES_INCLUDE="${ES_CONF_PATH}/elasticsearch.in.sh"
export JAVA_OPTS
export ES_JAVA_OPTS
export ES_HEAP_SIZE
export ES_HEAP_NEWSIZE
export ES_DIRECT_SIZE
export ES_USE_IPV4

server_command="/usr/share/elasticsearch/bin/elasticsearch"
server_args=" -p ${PIDFILE} -Des.path.conf=\"${ES_CONF_PATH}\" -Des.path.data=\"${ES_DATA_PATH}\" -Des.path.work=\"${ES_WORK_PATH}\" -Des.path.logs=\"${ES_LOG_PATH}\""

if [ -n "${ES_MAX_FD}" ]; then
    ulimit -n ${ES_MAX_FD}
fi

exec 2>&1
exec ${server_command} ${server_args}
