#!/bin/sh
# create default db if /var/lib/mysql is not mounted
if [ ! "$(ls /var/lib/mysql)" ]; then
    MYSQL_ROOT_PW="${MYSQL_ROOT_PW:-root}"
    MYSQL_ADMIN_USER="${MYSQL_ADMIN_USER:-root}"
    MYSQL_ADMIN_PW="${MYSQL_ADMIN_PW:-root}"
    /usr/share/mysql/scripts/mysql_install_db --basedir=/usr --log-bin=mysqld-bin && (/usr/sbin/mysqld --defaults-file=/etc/mysql/my.cnf --log-bin=mysqld-bin &) ; sleep 5 && /usr/bin/mysqladmin -u root password "${MYSQL_ROOT_PW}" && \
    mysql -u root --password="${MYSQL_ROOT_PW}" << EOF
DELETE FROM mysql.user WHERE User='';
DROP DATABASE test;
GRANT ALL ON *.* TO ${MYSQL_ADMIN_USER}@'%' IDENTIFIED BY "${MYSQL_ADMIN_PW}" WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF
killall mysqld && while ps -a | grep -q '[m]ysqld'; do sleep 1; done
fi

# handle backup cron
if [ -n "${BACKUP_CRON_SCHEDULE}" ] && [ ! -f /var/spool/cron/crontabs/root ]; then
    echo "${BACKUP_CRON_SCHEDULE} automysqlbackup" >> /var/spool/cron/crontabs/root
    chown root:root /backup
    sed -ri "s|^#CONFIG_backup_dir='/var/backup/db'|CONFIG_backup_dir='/backup'|" "/etc/automysqlbackup/automysqlbackup.conf"
    sed -ri "s|^#CONFIG_mysql_dump_password=''|CONFIG_mysql_dump_password='${MYSQL_ROOT_PW:-root}'|" "/etc/automysqlbackup/automysqlbackup.conf"
    sed -ri "s|^#CONFIG_multicore_threads=2|CONFIG_multicore_threads=${BACKUP_THREADS:-auto}|" "/etc/automysqlbackup/automysqlbackup.conf"
    sed -ri "s|^#CONFIG_mysql_dump_create_database='no'|CONFIG_mysql_dump_create_database='${BACKUP_CREATE_DB:-yes}'|" "/etc/automysqlbackup/automysqlbackup.conf"
    sed -ri "s|^#CONFIG_mysql_dump_compression='gzip'|CONFIG_mysql_dump_compression='${BACKUP_COMPRESSION_TYPE:-bzip2}'|" "/etc/automysqlbackup/automysqlbackup.conf"
    sed -ri "s|^#CONFIG_db_exclude=\( 'information_schema' \)|CONFIG_db_exclude=\(${BACKUP_EXCLUDE_DB:-information_schema performance_schema}\)|" \
        "/etc/automysqlbackup/automysqlbackup.conf"
    sed -ri "s|^#CONFIG_mysql_dump_latest='no'|CONFIG_mysql_dump_latest='${BACKUP_LATEST_LINK:-yes}'|" "/etc/automysqlbackup/automysqlbackup.conf"
    sed -ri "s|^#CONFIG_mysql_dump_latest_clean_filenames='no'|CONFIG_mysql_dump_latest_clean_filenames='${BACKUP_LATEST_CLEAN:-yes}'|" \
        "/etc/automysqlbackup/automysqlbackup.conf"
fi

exec 2>&1
exec /usr/sbin/mysqld --defaults-file=/etc/mysql/my.cnf --user=mysql --log-bin=mysqld-bin
