FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

ADD etc /etc

ENV ES_CLASSPATH /usr/share/elasticsearch/lib/*

RUN chmod +x $(find /etc/service -name run) && \
    ln -s /etc/s6_finish_default /etc/service/elasticsearch/finish && \
    ln -s /etc/service/elasticsearch /service

EXPOSE 9200 9300

CMD ["/bin/s6-svscan", "-t0", "/service"]
