#!/bin/sh

# create self signed certs if needed
if [ ! -f /etc/nginx/ssl/nginx.crt ] || [ ! -f /etc/nginx/ssl/nginx.key ]; then
    mkdir -p /etc/nginx/ssl
    CRT_COUNTRY="${CRT_COUNTRY:-DE}"
    CRT_STATE="${CRT_STATE:-SA}"
    CRT_LOCACTION="${CRT_LOCACTION:-MD}"
    CRT_ORG="${CRT_ORG:-ACME Inc - nginx}"
    CRT_CN="${CRT_CN:-nginx.local}"
    openssl req -x509 -nodes -days 3650 -newkey rsa:4096 \
        -subj "/C=${CRT_COUNTRY}/ST=${CRT_STATE}/L=${CRT_LOCACTION}/O=${CRT_ORG}/CN=${CRT_CN}" \
        -keyout /etc/nginx/ssl/nginx.key \
        -out /etc/nginx/ssl/nginx.crt 
fi

exec 2>&1
exec /usr/sbin/nginx
