FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

VOLUME ["/etc/nginx/sites-enabled"]

COPY fix_cert_links.sh /bin/fix_cert_links.sh

# run fix_cert_links.sh when /etc/nginx/sites-enabled/default.conf changes
ENV WATCHER_FS_CMD ls /etc/nginx/sites-enabled/default.conf
ENV WATCHER_ONCHANGE fix_cert_links.sh
RUN ln -s /etc/service/fs-watcher /service
