FROM ${NAMESPACE}/busybox
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

#ADD etc /etc

#RUN chmod +x $(find /etc/service -name run) && ln -s /etc/service/* /service

RUN ldconfig

CMD ["/bin/s6-svscan", "/service"]
