#!/bin/bash

_help_command_description="Check for stage3 updates and sync portage container"

# ARGBASH_WRAP([opt-global])
# ARG_OPTIONAL_BOOLEAN([no-sync],[n],[Do not sync portage container, just check for stage3 updates])
# ARG_HELP([])
# ARGBASH_SET_INDENT([    ])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.3.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

die()
{
    local _ret=$2
    test -n "$_ret" || _ret=1
    test "$_PRINT_HELP" = yes && print_help >&2
    echo "$1" >&2
    exit ${_ret}
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_verbose=off
_arg_no_sync=off

print_help ()
{
    printf 'Usage: %s [--(no-)verbose] [--(no-)no-sync] [-h|--help]\n' "$0"
    printf "\t%s\n" "-n,--no-sync,--no-no-sync: Do not sync portage container, just check for stage3 updates (off by default)"
    printf "\t%s\n" "-h,--help: Prints help"
}

# THE PARSING ITSELF
while test $# -gt 0
do
    _key="$1"
    case "$_key" in
        --no-verbose|--verbose)
            _arg_verbose="on"
            _args_opt_global_opt+=("${_key%%=*}")
            test "${1:0:5}" = "--no-" && _arg_verbose="off"
            ;;
        -n*|--no-no-sync|--no-sync)
            _arg_no_sync="on"
            _next="${_key##-n}"
            test -n "$_next" && test "$_next" != "$_key" && shift && set -- "-n" "-${_next}" "$@"
            test "${1:0:5}" = "--no-" && _arg_no_sync="off"
            ;;
        -h*|--help)
            print_help
            exit 0
            ;;
        *)
            _PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
            ;;
    esac
    shift
done

# OTHER STUFF GENERATED BY Argbash
_args_opt_global=("${_args_opt_global_opt[@]}" "${_args_opt_global_pos[@]}")

### END OF CODE GENERATED BY Argbash (sortof) ### ])
