#!/bin/sh

echo "php-fpm: waiting for nginx to start.."
until ps -o comm | grep -q nginx; do
    sleep 1
done

exec 2>&1
exec /usr/bin/php-fpm5.5 -y /etc/php/fpm-php5.5/php-fpm.conf -F >> /var/log/php5-fpm.log
